import Head from "next/head";
import Features from "../components/homepage/features";
import Trending from "../components/homepage/trending";
import Button from "../components/ui/button";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Food Express App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer
        position="top-right"
        autoClose={1500}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover={false}
        theme="light"
      />

      <section className="bg-primary text-white md:min-h-[400px] py-8 lg:pl-28 md:pl-16 flex justify-between md:flex-row flex-col-reverse px-5 md:px-0 ">
        <div className="left-area mt-10 md:mt-32 flex-1">
          <h2 className="md:text-[70px] text-[50px] font-bold leading-[50px] md:leading-[70px]">
            Fresh Food <br /> Delivered FAST{" "}
          </h2>
          <p className=" mt-5 ">
            Order your favorite food online with a tap of a button.{" "}
          </p>

          <Button className="my-5">Order Now</Button>
        </div>

        <div className="right-area flex justify-end flex-1">
          <img
            src="/pizza-hero.png"
            alt=""
            className="hidden md:block md:h-[540px] "
          />
        </div>
      </section>

      <Features />
      <Trending />
    </div>
  );
}
